kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

    </settings>
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonarqube-secret-token
spec:
  encryptedData:
    sonar-project.properties: AgB8G99dDeiSMe5TE11IWUZvaGoR+x8MZED9jtbUYiGal2WUp56jt+jIgjBOhpT3z0Cxz7Dv10udvqd+MjkgCej3e19JP51nYDnHuIh0XtREqsGgKXNoNNpe+JL1qmnZrrz1Ej4uTsLxuvXUN5wSiV4xsPn4atLegG03BEu7O3aCXVcDMhA3sZOsF0B4RhAfQgsTPWIhUBTZqZ9BOZ8akB2r5r46wRKcnToGCuwLPzgtx/k6IeZpPxZIlXu3rTjVqPA1yWNw/NQOhlnfDayI3FvwKdOmAztgifkutx+fM9R43mLJXoQjKwwm6A1jFH7re7Sz1nmlb6WOHL49tjgZiX0Y5bOZnsheCCuLbh3tocPXRIO+kGsVv9hYNbICY7ZdQYVrg/2cTow5x05FQb7IoQSedYzOyVZIq4MGPPAM83HCVu/TzN01nHtVgOKjz7HOf1WBe1qpXR4w/1T/CxU6fC6icE+oaA+FdasTRa8NqCOHIQIpOgLXiwhsrxveFztCjaRMM2liyfxywcZ5e+kC8+7HKCDhVLkP2TRtJwp7I4TSKIf1wATkVNlHYqKuZzjIkG+QIDsIRmAXZh3aaqHXEJZ/OuwUg5yBo3eV16j6UTzThO9sg9IELsdxdGk9HMnDvj0y9cOXWaNA3wCZNAU8jTWyLfDtMKw9TC0T1OrnGYyILVV4uOeU04/aD/8RuWw7hmW7ulQwB8P2zQ8xNHlJvsnN6XT/1DcnOB7Dk6EU9DTMI2YkQiB6dh48qZyE6fny34ApujoWuifPjr89TLi5W7F5dGg7Hd7LFYoMsT2yeT7u5AMrgLFaBR6axPOIKEYVj7sxXGIYtMR/JNrEOg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonarqube-secret-token
    type: Opaque