spring.application.name: ${{ values.appName }}

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true

spring:
  ai:
    openai:
      base-url: https://${{ values.aiModelName }}-${{ values.aiModelNamespace }}.${{ values.clusterDomain }}
      chat:
        options:
          model: ${{ values.aiModelName }}