spring.application.name: ${{ values.appName }}

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true

spring:
  ai:
    ollama:
      base-url: ${{ values.aiModelEndpoint }}
      chat:
        options:
          model: ${{ values.aiModelName }}